name: rick_and_morty_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  firebase_auth: ^4.2.3
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  mocktail: ^0.3.0
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  # fonts:
  #   - family: 
  #     fonts: 
  #       - asset: assets/fonts/Roboto-Regular.ttf
